import { useSyncExternalStore } from 'react'

// The languages (and dialects) the site can translate into, picked on the Settings page. Each one needs
// its own Cheatsheet data, generated by scripts/build-cheatsheet.ts (which reads this list). Only what
// which-dialect can translate English into belongs here: Vietnamese's three dialects for now; more
// languages as the package adds them.

export type TargetLanguage = {
  // Saved in settings and used in data file names: "vi-Southern" → public/cheatsheet/top-100.vi-Southern.json.
  id: string
  // which-dialect's language code and region.
  code: string
  region?: string
  // "Vietnamese" and "Southern": the Settings page groups dialects under their language.
  language: string
  dialect?: string
  // How the rest of the site names it: "Southern Vietnamese".
  label: string
}

export const TARGET_LANGUAGES: TargetLanguage[] = [
  { id: 'vi-Southern', code: 'vi', region: 'Southern', language: 'Vietnamese', dialect: 'Southern', label: 'Southern Vietnamese' },
  { id: 'vi-Central', code: 'vi', region: 'Central', language: 'Vietnamese', dialect: 'Central', label: 'Central Vietnamese' },
  { id: 'vi-Northern', code: 'vi', region: 'Northern', language: 'Vietnamese', dialect: 'Northern', label: 'Northern Vietnamese' },
]

// Southern Vietnamese was the only language before Settings existed (2026-10-01).
export const DEFAULT_TARGET = TARGET_LANGUAGES[0]

const STORAGE_KEY = 'language-helper:target-language'
const CHANGE_EVENT = 'language-helper:target-language-change'
// Used when localStorage is unavailable: the choice then lasts until the page reloads.
let unsaved: string | null = null

export function targetById(id: string | null | undefined): TargetLanguage {
  return TARGET_LANGUAGES.find((t) => t.id === id) ?? DEFAULT_TARGET
}

function readTarget(): TargetLanguage {
  try {
    return targetById(localStorage.getItem(STORAGE_KEY) ?? unsaved)
  } catch {
    return targetById(unsaved)
  }
}

/** The language the site translates into, shared by every page and kept in sync across tabs. */
export function useTargetLanguage(): [TargetLanguage, (id: string) => void] {
  const target = useSyncExternalStore((onChange) => {
    // `storage` fires in other tabs; the custom event in this one.
    window.addEventListener('storage', onChange)
    window.addEventListener(CHANGE_EVENT, onChange)
    return () => {
      window.removeEventListener('storage', onChange)
      window.removeEventListener(CHANGE_EVENT, onChange)
    }
  }, readTarget)
  const setTarget = (id: string) => {
    try {
      localStorage.setItem(STORAGE_KEY, id)
    } catch {
      unsaved = id
    }
    window.dispatchEvent(new Event(CHANGE_EVENT))
  }
  return [target, setTarget]
}
